server:
  port: 8080
weather-service:
  url: http://localhost:8082
spring:
  data:
    mongodb:
      host: mongo
  datasource:
    url: jdbc:postgresql://postgres:5432/explorify
    username: root
    password: 1234
  jpa:
    open-in-view: false
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,env,beans,conditions,mappings,loggers,links,metrics
  endpoint:
    health:
      show-details: always
    env:
      show-values: always