weather-service:
  url: http://localhost:8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/explorify
    username: root
    password: 1234
  jpa:
    #    hibernate:
    #      ddl-auto: false
    open-in-view: false
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,env,beans,conditions,mappings,loggers,links,metrics
  endpoint:
    health:
      show-details: always
    env:
      show-values: always